on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          runTests: false
      - name: Formatter
        run: npm run formatter
      - name: Cypress run
        run: npm run cy:run
      - name: Generate html report
        run: npm run reporter
      # - name: Upload Results
      #   uses: actions/upload-artifact@v1
      #   if: always()
      #   with:
      #     name: cucumber-html-results
      #     path: ./allure-results 
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-html-report
          path: ./cypress/report 
      - name: Deploy reports
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          branch: report 
          folder: ./cypress/reports